name: Setup Environment

on:
  workflow_dispatch: # Manual trigger

jobs:
  setup:
    runs-on: self-hosted
    
    steps:
    - name: Update system packages
      run: |
        sudo apt update
        sudo apt upgrade -y
        
    - name: Install Docker (if not installed)
      run: |
        if ! command -v docker &> /dev/null; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo usermod -aG docker ubuntu
        fi
        
    - name: Install Docker Compose (if not installed)
      run: |
        if ! command -v docker-compose &> /dev/null; then
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        fi
        
    - name: Install Node.js (if not installed)
      run: |
        if ! command -v node &> /dev/null; then
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
        fi
        
    - name: Create project directory
      run: |
        mkdir -p /home/ubuntu/zerodha-clone
        
    - name: Setup environment variables
      run: |
        echo "NODE_ENV=production" >> /home/ubuntu/.bashrc
        echo "PORT=8080" >> /home/ubuntu/.bashrc
        
    - name: Verify installations
      run: |
        docker --version
        docker-compose --version
        node --version
        npm --version
